import { CaseStudyData } from "./types";

export const caseStudies: CaseStudyData[] = [
  {
    slug: "checkout-optimisation",
    projectName: "Officeworks, Checkout UX Optimisation",
    projectSlug: "OFFICEWORKS_CHECKOUT_OPTIMISATION",
    coordLabel: "CS_000 \u00B7 CRO / Experimentation \u00B7 2024\u20132025",
    title: "Checkout Optimisation",
    discipline: "CRO / Experimentation",
    meta: [
      { label: "Role", value: "UX & Experimentation Designer" },
      { label: "Timeline", value: "2024 \u2192 2025 \u00B7 Programme paused mid-2025" },
      { label: "Team", value: "CRO/Experimentation \u00B7 Design \u00B7 Analytics \u00B7 Dev Squad" },
      { label: "Tools", value: "Figma \u00B7 Miro \u00B7 Adobe Target \u00B7 Adobe Analytics \u00B7 Jira \u00B7 Confluence" },
      { label: "Scope", value: "Guest/Login UI \u00B7 Cart Review \u2192 Continue \u00B7 Mobile CTA Visibility \u00B7 Customer Details" },
    ],
    tldr: "A research-led, multi-test exploration to reduce Checkout friction and shorten the perceived journey, without changing payment mechanics. Led UX and experimentation across three streams: guest/login UI, Cart Review \u2192 Continue, and mobile-first CTA visibility. One desktop customer-details variant shipped to production; the programme was paused mid-2025 due to compounding roadblocks, with durable insights and design rules preserved for future enabling work.",
    overview: "The Officeworks Checkout is a shared web/app surface handling a wide range of customer types, guest, logged-in, loyalty members, across desktop and mobile. The optimisation program aimed to reduce friction and shorten the perceived journey without touching payment mechanics or back-end platform logic. Three parallel streams ran across 2024\u20132025, guest/login UI, Cart Review progression, and mobile CTA visibility, each structured as iterate-to-success experiments with clear hypotheses and guardrail metrics.",
    problem: "Customers experienced a confusing, hard-to-navigate checkout with friction editing the cart once inside. Delivery costs and availability appeared too late, loyalty and discount placement was unclear, and some UI patterns competed with the primary progression path. Platform constraints, how availability is populated after address entry, brittle payment-step behaviours, limited what could be solved through front-end tests alone.",
    insightCards: [
      { label: "Pain Point 01", text: "Cart editing friction, once inside checkout, customers found it difficult to modify their cart, creating confusion and abandonment at a high-value moment in the journey.", highlight: false },
      { label: "Pain Point 02", text: "Late delivery transparency, costs and availability surfacing too late in the flow created frustration and trust issues at the point of commitment.", highlight: false },
      { label: "Pain Point 03", text: "Mobile CTA visibility, primary Continue actions were consistently pushed below the fold on small screens by competing UI elements, creating a device-specific drop-off problem.", highlight: true },
    ],
    research: "Research combined customer feedback (NPS and internal notes), heuristic teardown, competitor analysis of checkout flows (guest-first affordance, fewer fields, early delivery transparency, progress indicators, express pay, sticky order summaries), and a FY25 Checkout experimentation plan. Four design principles framed the work: shorten the perceived journey, respect intent (guest-first by default), optimise for device realities, and operate within the stack.",
    researchCaption: "Heuristic teardown \u00B7 Checkout friction mapping across guest/login, cart review, and mobile CTA streams",
    processIntro: "The program ran across four phases, framing, experiments and iteration, shipping, and knowledge transfer, with three parallel streams each following an iterate-to-success model. Each A/B test included clear hypotheses, targeting, and primary/guardrail metrics. One variant shipped; the programme was paused mid-2025 with all insights consolidated into design rules for future enabling work.",
    processSteps: [
      { title: "Stream A, Guest/Login UI", text: "First attempt emphasised account/login within Customer Details, continuation was neutral but acquisition intent dipped. An iteration introduced side-by-side CTAs with value cues, improving login/registration intent while keeping continuation neutral. A targeted variant for recently-known customers removed irrelevant options. Desktop stacked CTA layout shipped to production." },
      { title: "Stream B, Cart Review \u2192 Continue", text: "First pass raised the primary Continue CTA above the fold, neutral/negative site-wide due to a large logged-in cohort preferring familiar affordance. Iteration restored familiar cues while maintaining prominence; behavioural signals moved in the right direction." },
      { title: "Stream C, Mobile CTA Visibility", text: "A sticky Continue CTA improved visibility but competed with high-value recommendation placements on small screens, neutral-to-negative continuation and a material drop in add-on behaviour. Not commercially viable in tested form." },
      { title: "Knowledge Transfer", text: "Programme paused mid-2025 due to technical blockers, stakeholder constraints, and a platform change that prevented live testing. Findings consolidated into design rules and operating guardrails for stakeholders, ready to reuse when enabling work unblocks deeper changes." },
    ],
    processCaption: "Three parallel experiment streams \u00B7 Guest/Login \u00B7 Cart Review \u00B7 Mobile CTA \u00B7 2024\u20132025",
    imgGrid2: [
      { alt: "Stream A \u00B7 Guest/Login UI iteration", caption: "Stream A \u00B7 Guest/Login UI, initial account emphasis vs side-by-side CTAs with value cues" },
      { alt: "Stream B \u00B7 Cart Review iteration", caption: "Stream B \u00B7 Cart Review, above-the-fold Continue vs prominence-with-familiarity" },
    ],
    solutionIntro: "The solution is a set of design patterns and guardrails, not a single shipped screen. One desktop customer-details variant is live in production; the remaining patterns are codified as design rules ready to scale when platform enabling work lands.",
    solutionTiles: [
      { title: "Guest-First with Value-Cued Login", text: "Keep guest checkout obvious. Side-by-side CTAs with succinct value proof when prompting for account/login. For recently-known customers, suppress irrelevant options to reduce choice friction. ~30% relative uplift in registration starts." },
      { title: "Cart Review Clarity", text: "Familiar, obvious Continue affordance for logged-in customers. Reduce below-the-fold dependency. Retire dead-click panels that look interactive but aren\u2019t." },
      { title: "Mobile Rules", text: "Ensure visibility of the primary action without permanently crowding the viewport or cannibalising upsell areas. Prefer contextual or progressive patterns over permanent sticky elements." },
      { title: "Scope Guardrails", text: "Focus optimisation where the team can ship sustainably, UI, sequencing, copy, validation, trust signals. Defer back-end-heavy ideas until enabling platform work makes them low-risk." },
    ],
    solutionCaption: "Shipped \u00B7 Desktop customer-details stacked CTA layout, now live in production",
    experiments: [
      { id: "CT-185", name: "Initial Account Emphasis", hypothesis: "Emphasising account/login within Customer Details will improve registration and login rates.", resultValue: "Neutral/negative", resultLabel: "Acquisition intent softened \u00B7 Iterate \u2192 CT-201" },
      { id: "CT-201", name: "Side-by-Side CTAs with Value Cues", hypothesis: "Side-by-side CTAs with value proof will improve login/registration intent without penalising continuation.", resultValue: "~30% relative \u2191", resultLabel: "Registration starts \u00B7 Winner \u2192 CT-214" },
      { id: "CT-214 \u2B50", name: "Desktop Stacked CTA Layout", hypothesis: "A stacked CTA layout for desktop Customer Details will improve clarity and acquisition signals.", resultValue: "Shipped", resultLabel: "Live in production" },
      { id: "CT-206", name: "Known Customer Targeting", hypothesis: "Removing irrelevant options for recently-known customers will reduce choice friction and improve login rates.", resultValue: "Positive", resultLabel: "Login attempts \u2191 \u00B7 Adopted" },
      { id: "CT-229", name: "Continue Above the Fold", hypothesis: "Raising the primary Continue CTA above the fold will improve checkout continuation.", resultValue: "Neutral/negative", resultLabel: "Familiar affordance disrupted \u00B7 Iterate \u2192 CT-237" },
      { id: "CT-237", name: "Prominence with Familiarity", hypothesis: "Restoring familiar cues while maintaining CTA prominence will improve continuation without penalising completion.", resultValue: "Positive direction", resultLabel: "Signals improved \u00B7 Led to CT-243" },
      { id: "CT-243", name: "Dead-Click Panel Simplification", hypothesis: "Removing non-clickable panels that generated dead clicks will reduce confusion and clarify the path to Continue.", resultValue: "Rules adopted", resultLabel: "Single CTA pattern codified" },
      { id: "CT-288", name: "Persistent Sticky Continue (Mobile)", hypothesis: "A persistent sticky Continue CTA on mobile will improve CTA visibility and checkout continuation.", resultValue: "Declined", resultLabel: "Add-on behaviour \u2193 \u00B7 Contextual alternative recommended" },
    ],
    outcomes: "One desktop customer-details variant (stacked CTA layout) shipped to production and is now part of the live experience. The broader programme was paused mid-2025 due to technical and stakeholder roadblocks. Insights and design rules are preserved and ready to resume. All outcomes are directional, no commercially sensitive metrics are published.",
    keyOutcome: "One variant shipped, the desktop stacked CTA layout is now live. Eight further experiments produced durable design rules and guardrails across guest/login, cart review, and mobile CTA streams, ready to scale when platform enabling work resumes.",
    reflection: "This work is best framed as research, exploration, and learning. It identified what helps, guest-first clarity, value-cued login, familiarity at key decision points, and what harms, crowding mobile viewports, competing with upsell at the wrong moment. The programme pause was frustrating but honest, shipping one strong pattern and preserving the rest as design rules is a better outcome than forcing changes that the platform couldn\u2019t sustain.",
  },
  {
    slug: "banana-barge",
    projectName: "Banana Barge",
    projectSlug: "BANANA_BARGE",
    coordLabel: "CS_001 \u00B7 Industrial Design \u00B7 2014",
    title: "Banana Barge",
    discipline: "Industrial Design",
    meta: [
      { label: "Role", value: "Industrial/Product Designer, Concept, CAD, Prototyping, Pilot, Production Handover" },
      { label: "Timeline", value: "Concept \u2192 Prototyping \u2192 6-month Pilot \u2192 National Rollout" },
      { label: "Team", value: "Internal design & fabrication; Coles produce team; offshore manufacturing" },
      { label: "Tools", value: "SolidWorks \u00B7 Materials sampling \u00B7 In-store trials" },
      { label: "Scope", value: "Retail fixture \u00B7 3 size variants \u00B7 500+ stores nationally" },
      { label: "Client", value: "Coles Supermarkets via iCreate Retail Solutions" },
      { label: "Rollout", value: "500+ stores nationally \u00B7 Australia-wide" },
    ],
    tldr: "Purpose-built banana display for Coles, maximising stock capacity while reducing bruising and waste. From SolidWorks CAD through prototyping, a 6-month pilot, and national production handover. Deployed across 500+ stores and still in use 10+ years later.",
    overview: "The Banana Barge is a purpose-built fresh produce display fixture designed for Coles Supermarkets, one of Australia\u2019s largest grocery retailers. With bananas being one of the highest-grossing items in the fresh produce section, Coles needed a fixture that could hold significantly more stock on the floor daily while protecting a notoriously fragile product.",
    problem: "Bananas are high-volume and high-value but physically fragile, existing display solutions weren\u2019t purpose-built for the product, leading to bruising, waste, and suboptimal capacity. Coles required a fixture that could increase daily on-floor stock, reduce damage through better geometry and surface treatment, adapt to different store footprints through modular sizing, and withstand the demands of a wet-clean retail environment over years of use.",
    insightCards: [
      { label: "Pain Point 01", text: "Existing display solutions caused bruising, contact surfaces and loading angles weren\u2019t designed for the fragility of bananas at scale.", highlight: false },
      { label: "Pain Point 02", text: "Fixed-size fixtures couldn\u2019t adapt to varied store footprints, a single solution needed to work across 500+ stores of different sizes.", highlight: false },
      { label: "Pain Point 03", text: "Hygiene, replenishment speed, and cleaning ease were non-negotiable operational constraints that had to be designed in from the start.", highlight: true },
    ],
    research: "Research focused on observing in-store replenishment behaviours and understanding operational constraints, reach, load height, stock flow from back-of-house to floor, and cleaning routines. Materials were benchmarked for hygiene performance, impact resistance, finish longevity, and suitability for a wet-clean environment.",
    researchCaption: "In-store observation \u00B7 Replenishment flow and load height constraints",
    processIntro: "The process moved from in-store observation and material benchmarking through SolidWorks CAD development, multiple prototype rounds, a formal in-store pilot, and offshore manufacture, with each phase directly informing the next.",
    processSteps: [
      { title: "CAD Development", text: "Full 3D definition, joint detailing, and bill of materials developed in SolidWorks. Stepped geometry established early to maximise display capacity and visibility while keeping the form manufacturable at scale." },
      { title: "Prototyping", text: "Multiple prototype rounds refining edge treatments, contact surface radii, and module interfaces, each iteration focused on reducing pressure points that cause bruising during loading and replenishment." },
      { title: "In-Store Pilot", text: "6-month trial at Coles Brighton validated capacity, replenishment flow, cleaning ease, and damage reduction in a live retail environment." },
      { title: "Manufacturing & Rollout", text: "Offshore production managed through fabrication partners, with national deployment across 500+ Coles supermarkets. Modular construction simplified logistics." },
    ],
    processCaption: "SolidWorks assembly \u00B7 Exploded view showing module interfaces and joinery",
    pilotInfo: { location: "Coles Brighton", duration: "6 months", outcome: "National rollout, 500+ stores", findings: "Validated on-floor capacity increase, replenishment ease, cleaning performance, and damage reduction. Edge refinements from prototype rounds confirmed effective in live conditions." },
    imgGrid2: [
      { alt: "Pilot installation at Coles Brighton", caption: "Pilot installation \u00B7 Coles Brighton \u00B7 6-month trial" },
      { alt: "SolidWorks exploded view", caption: "SolidWorks exploded view \u00B7 Module interfaces, joinery and material callouts" },
    ],
    solutionIntro: "The Banana Barge is a stepped, oval-form display fixture in three modular sizes, built from Victorian Ash timber, 304 stainless steel, and 6mm Haircell ABS.",
    solutionTiles: [
      { title: "Stepped Geometry", text: "Tiered display surface increases on-floor stock capacity and product visibility while keeping the fixture accessible for both shoppers and staff during replenishment." },
      { title: "Modular Construction", text: "Three size variants, Small, Medium, Large, built from the same modular components. Flat-pack transport, straightforward in-store assembly." },
      { title: "Material Selection", text: "Victorian Ash for structural warmth, 304 stainless steel for hygiene durability, 6mm Haircell ABS for thermoformed contact surfaces." },
      { title: "Shopper Convenience", text: "Integrated plastic bag dispenser positioned at the natural reach point, a small detail that removes friction at the moment of purchase." },
    ],
    solutionCaption: "Banana Barge installed at Coles Brighton \u00B7 Modular oval form with stepped ABS display surface",
    clientCredit: { client: "Coles Supermarkets", via: "iCreate Retail Solutions Pty. Ltd." },
    outcomes: "The Banana Barge was deployed nationally across 500+ Coles supermarkets following the successful Coles Brighton pilot. Still in use 10+ years after initial rollout.",
    keyOutcome: "Deployed across 500+ Coles supermarkets nationally and still in use 10+ years later, a fixture that outlasted the brief and became a long-term operational standard.",
    reflection: "This project reinforced how small geometry and material choices directly influence product preservation and store workflows, details that are invisible to shoppers but critical to the people using the fixture every day. The 6-month pilot was the most valuable part of the process.",
  },
  {
    slug: "ikea-make-room-for-life",
    projectName: "IKEA, Make Room for Life",
    projectSlug: "IKEA_MAKE_ROOM_FOR_LIFE",
    coordLabel: "CS_002 \u00B7 Retail Spatial Design \u00B7 2018",
    title: "IKEA, Make Room for Life",
    discipline: "Retail Spatial Design",
    meta: [
      { label: "Role", value: "Retail Design Specialist / Deputy Communication & Design Manager" },
      { label: "Timeline", value: "FY18\u2013FY19 planning and multi-store rollout" },
      { label: "Team", value: "Com&In (VM/Graphics) \u00B7 Sales \u00B7 In-Store Logistics \u00B7 Contractors" },
      { label: "Tools", value: "AutoCAD \u00B7 Revit \u00B7 SketchUp \u00B7 CSP guidelines" },
      { label: "Scope", value: "Living Room compacts \u00B7 Sofas \u00B7 Armchairs \u00B7 Hot spots \u00B7 Podiums \u00B7 VM" },
      { label: "Client", value: "IKEA Systems BV via IKEA UK & Ireland" },
      { label: "Rollout", value: "Multi-store \u00B7 UK & Ireland \u00B7 FY18\u2013FY19" },
    ],
    tldr: "Full Living Room department rebuild for IKEA UK & Ireland, function-first grouping, hot-spot planning, and coordinated VM to improve range overview, inspiration, and commercial clarity.",
    overview: "In 2018 IKEA launched \u201CMake Room for Life\u201D across the UK and Ireland, a campaign and department rebuild examining how flexible, well-organised living rooms support the way people actually live at home.",
    problem: "The Living Room area needed to present a wide, fast-changing sofa and armchair range in a way that was inspiring, easy to navigate, and commercially effective, across stores with different footprints and evolving seasonal ranges.",
    insightCards: [
      { label: "Pain Point 01", text: "No clear range overview, customers couldn\u2019t quickly distinguish function, style, or price tier without significant browsing effort.", highlight: false },
      { label: "Pain Point 02", text: "Price/quality ladders were invisible, lowest-price options weren\u2019t surfaced at entry.", highlight: false },
      { label: "Pain Point 03", text: "Add-on sales and coordinated solutions were disconnected from the seating offer.", highlight: true },
    ],
    research: "Research was aligned to IKEA\u2019s Common Store Planning (CSP) guidance for FY18\u2013FY19, a global framework developed from shopper behaviour studies and commercial performance analysis.",
    researchCaption: "CSP guidance extract \u00B7 Function \u2192 style \u2192 family grouping logic and hot-spot locations",
    processIntro: "The process moved from global CSP guidance interpretation through macro planning, VM and communication integration, and inspiration/add-on sales design.",
    processSteps: [
      { title: "Macro Planning", text: "Defined the Sofa compact (~521m\u00B2) and Armchair compact (~83m\u00B2) with low walls for clear sight lines and single flooring for flexibility." },
      { title: "VM & Communication Integration", text: "Established display racking for width-and-depth impressions, fronta/repetition for clarity, and A4 overview signs for families with many shape and fabric options." },
      { title: "Inspiration & Add-On Sales", text: "Positioned activity podiums and perimeter breaks to punctuate the compact, support seasonality, and reinforce Democratic Design." },
      { title: "Store Rollout Package", text: "Developed a complete concept package, CAD plans, SketchUp elevations, VM playbooks, and finish/furniture specifications, sent to all UK & Ireland stores." },
    ],
    processCaption: "SketchUp concept elevation \u00B7 Customer walkthrough of the Living Room department entry",
    imgGrid2: [
      { alt: "Combined compact floor plan", caption: "Combined compact floor plan \u00B7 Sofa + Armchair zones, hot spots, and aisle prolongations" },
      { alt: "VM & communication", caption: "VM & communication \u00B7 A4 overview signs, price ladders, and fabric sample stations" },
    ],
    imgGrid3: [
      { alt: "IKEA Leeds implementation", caption: "IKEA Leeds \u00B7 Make Room for Life implementation" },
      { alt: "IKEA Leeds armchair compact", caption: "IKEA Leeds \u00B7 Armchair compact and Democratic Design hot spot" },
      { alt: "IKEA Leeds sofa solution", caption: "IKEA Leeds \u00B7 Coordinated sofa solution with add-on styling" },
    ],
    spaceMetrics: [
      { area: "521", unit: "m\u00B2", label: "Sofa Compact" },
      { area: "83", unit: "m\u00B2", label: "Armchair Compact" },
      { area: "20+", unit: "stores", label: "UK & Ireland Rollout" },
    ],
    solutionIntro: "A function-first Living Room department built around clear grouping logic, hot-spot strategy, and price/quality ladders.",
    solutionTiles: [
      { title: "Grouping & Navigation", text: "Sofas grouped by function first (no-sleep \u2192 sleep), then style, then family." },
      { title: "First Impressions & Hot Spots", text: "Low-price perception surfaced at entry with accessible price signs on top families." },
      { title: "Price & Quality Ladders", text: "Lowest, mid, and high-price tiers placed side by side for easy comparison." },
      { title: "Add-On Sales & Coordination", text: "Cushions, throws, and lighting positioned with seating throughout the compact." },
    ],
    solutionCaption: "Concept package \u00B7 SketchUp isometric showing full Living Room department layout",
    designPrinciples: [
      { title: "Function-First Grouping", text: "Primary grouping by function (sleep/no-sleep) before style or family." },
      { title: "Hot-Spot Planning", text: "Top families and key messages positioned at aisle prolongations." },
      { title: "Price/Quality Ladder", text: "Lowest, mid, and high-price tiers made visible and comparable." },
      { title: "Width & Depth Display", text: "Racking and fronta/repetition techniques created impact without clutter." },
      { title: "Add-On Integration", text: "Accessories positioned with seating throughout, not in a separate section." },
    ],
    clientCredit: { client: "IKEA Systems BV", via: "IKEA UK & Ireland, Retail Design / Com&In" },
    outcomes: "The department rebuild delivered a clearer range overview and a more inspiring journey through the seating offer. Outcomes are directional, no commercially sensitive metrics are published.",
    keyOutcome: "A function-first Living Room compact rolled out across IKEA UK & Ireland, delivering clearer range overview, stronger first impressions, and a flexible structure that adapts to evolving ranges.",
    reflection: "Balancing global brand guidance with local store constraints was the central challenge, and the most valuable lesson. The strongest levers were function-first grouping, hot-spot planning, and clear price/quality ladders.",
  },
  {
    slug: "through-the-woods",
    projectName: "Through the Woods",
    projectSlug: "THROUGH_THE_WOODS",
    coordLabel: "CS_003 \u00B7 Industrial Design \u00B7 2022",
    title: "Through the Woods",
    discipline: "Industrial Design",
    meta: [
      { label: "Role", value: "Toy Design, Product Development, Material Sourcing" },
      { label: "Timeline", value: "Seasonal A/W Collection, Trend \u2192 Materials \u2192 Range \u2192 Construction" },
      { label: "Team", value: "Solo design & product development \u00B7 Manufacturing liaison" },
      { label: "Tools", value: "Pattern drafting \u00B7 Soft-goods construction \u00B7 Materials sourcing \u00B7 Wooden prototyping" },
      { label: "Scope", value: "Costumes \u00B7 Oversized Plush D\u00e9cor \u00B7 Character Plush \u00B7 Wooden Activity Sets" },
    ],
    tldr: "Nature-inspired, screen-free toy range for Autumn/Winter, costumes, oversized plush d\u00e9cor, character plush, and wooden activity sets. Designed around sustainable materials (rPET, organic cotton, hemp-based faux fur, FSC pine) and child-safe construction throughout.",
    overview: "Through the Woods is a seasonal A/W toy range designed to reconnect children with nature and create a screen-free play world.",
    problem: "Design an Autumn/Winter toy collection that reflects current children\u2019s trends, uses eco-friendly materials and ethical production, delivers tactile learning and imaginative play, and meets child safety standards across four distinct product categories.",
    insightCards: [
      { label: "Pain Point 01", text: "Sustainability requirements ruled out conventional materials, every SKU needed eco-friendly alternatives.", highlight: false },
      { label: "Pain Point 02", text: "Four distinct product categories, soft goods, plush, wooden, each with different construction methods and safety requirements.", highlight: false },
      { label: "Pain Point 03", text: "Range cohesion across very different product types, all needed to tell one unified forest story.", highlight: true },
    ],
    research: "Research focused on current A/W children\u2019s product trends to identify the pillars shaping the category. Material research benchmarked sustainable alternatives across all construction methods.",
    researchCaption: "Trend direction \u00B7 Natural finishes, organic forms, muted palette, conscious product values",
    processIntro: "The process moved from trend research and material benchmarking through pattern and construction testing, to range cohesion.",
    processSteps: [
      { title: "Materials Exploration", text: "Prioritised sustainable content across all SKUs, rPET felts, BCI organic cottons, EcoPel hemp-based faux fur, FSC-sourced pine." },
      { title: "Pattern & Construction Testing", text: "Upholstery-style builds for oversized plush, dense foam core with organic cotton padding, for durability in daily use." },
      { title: "Range Cohesion", text: "A shared flora and fauna story threads through all four categories." },
      { title: "Safety & Compliance", text: "All product decisions driven by child-safe construction principles, embroidered facial features, sealed edges, non-toxic pigments." },
    ],
    processCaption: "Sustainable material stack \u00B7 rPET felt, EcoPel hemp faux fur, BCI organic cotton, FSC pine",
    imgGrid2: [
      { alt: "Costumes detail", caption: "Costumes \u00B7 Tree Top Owl + Woodland Red Fox \u00B7 rPET felt and EcoPel hemp faux fur" },
      { alt: "Oversized Plush detail", caption: "Oversized Plush \u00B7 Giant Mushroom + Giant Leaf \u00B7 upholstery-style construction" },
    ],
    solutionIntro: "A four-category A/W toy range, costumes, oversized plush d\u00e9cor, character plush, and wooden activity sets, unified by a nature story.",
    solutionTiles: [
      { title: "Costumes", text: "Tree Top Owl and Woodland Red Fox, masks, capes, cowls, and spats in rPET recycled polyester and EcoPel hemp faux fur." },
      { title: "Oversized Plush D\u00e9cor", text: "Giant Mushroom and Giant Leaf Cushion, upholstery-style builds with recycled composite chip foam cores." },
      { title: "Character Plush", text: "Freya Fox, Daisy the Pixie, and Lily Rabbit, EcoPel hemp-based cotton outers, embroidered facial features." },
      { title: "Wooden Play", text: "Activity Treehouse and Memory Tile Game, FSC pine, flat-pack, non-toxic matt sealant and natural pigments." },
    ],
    solutionCaption: "Through the Woods range \u00B7 Costumes, Oversized Plush, Character Plush, Wooden Play",
    materials: [
      { name: "rPET Felt", spec: "100% recycled polyethylene terephthalate \u00B7 felted polyester sheet", use: "Costume masks \u00B7 Plush outers \u00B7 Non-skid bases", swatch: "#D8D4CC" },
      { name: "EcoPel Hemp Faux Fur", spec: "Hemp-based faux fur \u00B7 ethical synthetic alternative", use: "Costume cowls & spats \u00B7 Character plush outers", swatch: "#C4B49A" },
      { name: "BCI Organic Cotton", spec: "Better Cotton Initiative certified \u00B7 organic grade", use: "Plush fill \u00B7 Lining \u00B7 Character apparel", swatch: "#F0EDE8" },
      { name: "FSC Pine", spec: "FSC-certified pine/plywood \u00B7 non-toxic matt sealant", use: "Activity Treehouse \u00B7 Memory Tile Game", swatch: "#C8A97A" },
    ],
    productRange: [
      { name: "Costumes", detail: "Tree Top Owl + Woodland Red Fox \u00B7 Unisex 2\u20136 \u00B7 rPET + EcoPel hemp faux fur" },
      { name: "Oversized Plush", detail: "Giant Mushroom + Giant Leaf Cushion \u00B7 upholstery-style \u00B7 rPET + organic cotton" },
      { name: "Character Plush", detail: "Freya Fox \u00B7 Daisy the Pixie \u00B7 Lily Rabbit \u00B7 EcoPel hemp cotton + embroidered features" },
      { name: "Wooden Play", detail: "Activity Treehouse + Memory Tile Game \u00B7 FSC pine \u00B7 non-toxic pigments" },
    ],
    outcomes: "A cohesive, nature-inspired play world with up to ~80% sustainable material content across SKUs.",
    keyOutcome: "A four-category A/W toy range unified by a single nature story, with sustainable materials at the core of every construction decision and child safety built in from the start.",
    reflection: "This range reinforced why material choice and construction detail matter for children\u2019s products, durability, safety, and tactile feel are as important as the look.",
  },
  {
    slug: "la-bohemia",
    projectName: "La Bohemia",
    projectSlug: "LA_BOHEMIA",
    coordLabel: "CS_004 \u00B7 Web Design \u00B7 2021",
    title: "La Bohemia",
    discipline: "Web Design",
    meta: [
      { label: "Role", value: "Web Design, UX/UI, IA, Wireframing, WIX Build" },
      { label: "Timeline", value: "Concept \u2192 Wireframes \u2192 WIX Configuration" },
      { label: "Team", value: "Solo design & build \u00B7 Owner-operators as stakeholders" },
      { label: "Tools", value: "WIX \u00B7 rankingCoach \u00B7 Ascend \u00B7 Figma" },
      { label: "Scope", value: "Home \u00B7 Menus \u00B7 Reservations \u00B7 Order Online \u00B7 Gallery \u00B7 Contact" },
    ],
    tldr: "Website for an authentic Chilean caf\u00e9 & bar to move beyond a social-only presence. Task-first IA with WIX plugins for online orders, reservations, and menus.",
    overview: "La Bohemia is an authentic Chilean caf\u00e9 & bar in Melbourne\u2019s south-east, a family business built on culture, quality, and community.",
    problem: "La Bohemia had no website, only social media. Potential customers had no reliable way to see menus, make reservations, or place online orders without calling or messaging directly.",
    insightCards: [
      { label: "Pain Point 01", text: "No owned web presence, menus, bookings, and orders all depended on social media DMs or phone calls.", highlight: false },
      { label: "Pain Point 02", text: "Competitor analysis showed all three local benchmarks lacked cohesive branding and clear task access.", highlight: false },
      { label: "Pain Point 03", text: "Owners needed full autonomy to update menus, promotions, and events, a custom build was not viable.", highlight: true },
    ],
    research: "Competitor analysis benchmarked three local restaurants. WIX was assessed against Weebly and Squarespace across ease of use, design/customisation, plugins, e-commerce, SEO, support, and pricing.",
    researchCaption: "Competitor analysis \u00B7 Three restaurants benchmarked on structure, booking clarity, and branding",
    processIntro: "The process moved from competitor analysis through IA definition, wireframing, design system development, and WIX configuration.",
    processSteps: [
      { title: "Task-First IA", text: "Defined the site structure around three primary tasks: Order, Book, Menus." },
      { title: "Wireframes", text: "Built wireframes for Home, Menus, and Reservations, proving the above-the-fold CTA logic." },
      { title: "Design System", text: "Established typography (Avenir LT Std + Courier), a warm Chilean-inspired palette, and a moodboard." },
      { title: "WIX Configuration", text: "Configured WIX Orders, Menus, Reservations, and Social Bar. Set up rankingCoach for local SEO hygiene." },
    ],
    processCaption: "Lo-fi wireframes \u00B7 Home, Menus, Reservations",
    imgGrid2: [
      { alt: "Design system", caption: "Design system \u00B7 Avenir + Courier \u00B7 warm Chilean palette" },
      { alt: "Moodboard", caption: "Moodboard \u00B7 Chilean street culture, food photography, community" },
    ],
    solutionIntro: "A WIX site built around three primary tasks surfaced on every page, Order, Book, Menus.",
    solutionTiles: [
      { title: "Orders & Menus", text: "WIX Orders handles pickup/delivery with multiple payment options. WIX Menus supports time-based and specialty menus." },
      { title: "Reservations", text: "WIX Reservations provides self-serve table bookings around the clock." },
      { title: "Social & SEO", text: "Restaurant Social Bar integrates Instagram, Facebook, and Zomato. rankingCoach handles local SEO hygiene." },
      { title: "Owner Autonomy", text: "Full handover documentation and training so owners can update menus, post promotions, and manage bookings independently." },
    ],
    solutionCaption: "Final WIX build \u00B7 Home, Menus, Reservations, Order Online",
    techStack: [
      { value: "WIX", primary: true },
      { value: "WIX Orders", primary: true },
      { value: "WIX Menus", primary: false },
      { value: "WIX Reservations", primary: false },
      { value: "rankingCoach", primary: false },
      { value: "Ascend / Mailchimp", primary: false },
    ],
    clientCredit: { client: "La Bohemia Caf\u00e9 & Bar", via: "Solo commission" },
    outcomes: "A task-first website that connects the dots between social discovery and on-site action.",
    keyOutcome: "La Bohemia moved from social-only to a fully functional owned web presence, with orders, reservations, and menus all live and owner-managed from day one.",
    reflection: "This was a pragmatic build: prioritise tasks, choose tools the owners can maintain, and keep the design warm but uncluttered.",
  },
  {
    slug: "medipal",
    projectName: "MediPal",
    projectSlug: "MEDIPAL",
    coordLabel: "CS_005 \u00B7 UX/UI \u00B7 2021",
    title: "MediPal",
    discipline: "UX/UI Design",
    meta: [
      { label: "Role", value: "UX Research, IA, User Flows, Wireframing, Prototype, Usability Testing" },
      { label: "Timeline", value: "Research \u2192 IA \u2192 User Flows \u2192 Wireframes \u2192 Prototype \u2192 Testing" },
      { label: "Team", value: "Solo UX \u00B7 7 research participants \u00B7 40 survey respondents \u00B7 4 usability testers" },
      { label: "Tools", value: "Axure \u00B7 Miro \u00B7 SurveyMonkey" },
      { label: "Scope", value: "Login \u00B7 Dashboard \u00B7 Search \u00B7 Book Appointment \u00B7 Treatments \u00B7 Live Tracking" },
    ],
    tldr: "MediPal is a healthcare app concept designed to centralise appointment booking, real-time tracking, and treatment management across multiple practitioners. Validated through usability testing with 4 participants, averaging 8 minutes 17 seconds task completion with strong satisfaction scores.",
    overview: "MediPal is a web and mobile app concept that lets users book appointments across multiple healthcare providers, track appointments in real time, check in contactlessly, and centralise their prescriptions and treatment records in one place.",
    statStrip: [
      { number: "7", label: "Qualitative Interviews" },
      { number: "40", label: "Survey Respondents" },
      { number: "8m 17s", label: "Avg. Task Completion" },
    ],
    problem: "Managing healthcare needs across multiple practitioners is fragmented and inefficient. Users juggle separate apps per clinic, sit in waiting rooms with no visibility on delays, manage prescriptions on paper, and manually track appointment times.",
    insightCards: [
      { label: "Pain Point 01", text: "Appointment wait times, 50% of survey respondents said live updates and tracking would most improve their experience.", highlight: false },
      { label: "Pain Point 02", text: "App fragmentation, active users had to manage a different booking app for every practitioner.", highlight: false },
      { label: "Pain Point 03", text: "Treatment tracking, 20% had no tracking system at all; scripts were kept on paper, easily lost or damaged.", highlight: true },
    ],
    research: "Research combined qualitative interviews (7 participants over 1 week) with a quantitative survey (40 respondents) to understand how people manage their healthcare needs.",
    researchCaption: "Customer journey map \u00B7 Awareness \u2192 Browse \u2192 Book \u2192 Attend \u2192 Post-appointment",
    personas: [
      { name: "Jason Daniels", role: "Current App/Service User \u00B7 Age 34 \u00B7 Warrandyte", bio: "Charter pilot with a busy lifestyle managing GP, Physio, and Dietician appointments across multiple apps. Frustrated by appointment availability, waiting room time, and having to re-enter personal information." },
      { name: "Paulette Vlotman", role: "Non-App/Service User \u00B7 Age 58 \u00B7 Glen Waverley", bio: "Part-time admin assistant managing ongoing health conditions with frequent visits. Currently manages all appointments manually via calendar and paper scripts. Open to digital if intuitive." },
    ],
    researchQuote: { text: "The waiting time. Sometimes we\u2019re there for an hour or two, and it gets boring and you tend to get impatient. That\u2019s my main Gripe.", attribution: "Paulette Vlotman \u00B7 Non-App/Service User Persona" },
    processIntro: "The process moved from qualitative and quantitative research through IA definition, user flow mapping, annotated wireframing, Axure prototype build, and moderated usability testing.",
    processSteps: [
      { title: "Information Architecture", text: "Defined a 7-level app hierarchy, Splash, Onboarding, Register/Login, Dashboard, Appointments, Treatments, Search, Account." },
      { title: "User Flow Mapping", text: "Three core flows mapped in Miro, Login/Register, Book Appointment, and Track Booking/Appointment Schedule." },
      { title: "Annotated Wireframes & Prototype", text: "15 annotated wireframe screens built in Axure covering every primary flow." },
      { title: "Usability Testing (n=4)", text: "Four participants completed scripted tasks averaging 8m 17s. Task 4 (live update/notifications) generated the most errors." },
    ],
    processCaption: "Annotated wireframes \u00B7 Axure prototype, Dashboard, Search, Book Appointment, Live Update",
    imgGrid2: [
      { alt: "User flow - Book Appointment", caption: "User flow \u00B7 Book Appointment, dual pathway by location or practitioner" },
      { alt: "User flow - Login/Register", caption: "User flow \u00B7 Login/Register and Track Booking/Appointment Schedule" },
    ],
    solutionIntro: "MediPal brings appointment booking, real-time tracking, contactless check-in, and treatment management into a single intuitive app.",
    solutionTiles: [
      { title: "Search & Book", text: "Search by provider/clinic name, speciality, or suburb/postcode. Dual booking pathway, existing or new patient." },
      { title: "Real-Time Tracking", text: "Live departure prompts adjust in real time based on the practitioner\u2019s running schedule." },
      { title: "Contactless Check-In", text: "NFC-based check-in notifies the clinic of arrival with minimal physical interactions." },
      { title: "Treatment & Script Wallet", text: "Current and historical scripts and treatments stored digitally, accessible at any time." },
    ],
    solutionCaption: "High-fidelity screens \u00B7 Splash, Dashboard, Search, Appointment Info, Live Update",
    youtubeEmbed: "https://youtu.be/PYPX9-h2064?si=baZOZvTmRYZqXoUn",
    outcomes: "Usability testing confirmed the app had a familiar, functional format, all participants completed tasks in an average of 8m 17s and expressed strong overall satisfaction.",
    keyOutcome: "A fully tested Axure prototype across 15 screens and 3 core flows, with 100% task completion on Login, Search, and Booking, and clear, actionable findings on notification UX.",
    reflection: "The research surfaced a meaningful split between user segments. The usability test was most valuable in exposing the notification/live update flow as counterintuitive.",
  },
  {
    slug: "acre-organics",
    projectName: "Acre Organics",
    projectSlug: "ACRE_ORGANICS",
    coordLabel: "CS_006 \u00B7 UX/UI \u00B7 2020",
    title: "Acre Organics",
    discipline: "UX/UI Design",
    meta: [
      { label: "Role", value: "UX Research, IA, Wireframing, Usability Testing" },
      { label: "Timeline", value: "Research \u2192 IA \u2192 Wireframes \u2192 Testing \u2192 Iteration" },
      { label: "Team", value: "Solo UX \u00B7 5 research participants \u00B7 5 usability participants" },
      { label: "Tools", value: "Figma \u00B7 Miro" },
      { label: "Scope", value: "Home \u00B7 Category Landing \u00B7 PLP \u00B7 PDP \u00B7 Recipes \u00B7 Returns" },
    ],
    tldr: "Online grocery experience focused on quality, Australian-grown produce, and reusable packaging. Research-led IA and wireframes; usability testing drove clearer navigation and reduced reliance on predictive search.",
    overview: "Acre Organics is an online grocery experience built around a simple idea: Australian-grown produce, delivered to your door in eco-friendly, reusable packaging.",
    statStrip: [
      { number: "5", label: "Research Interviews" },
      { number: "5", label: "Usability Participants" },
      { number: "8m 53s", label: "Avg. Task Completion" },
    ],
    problem: "Shoppers want fresh, local produce and less packaging waste, but they also expect quick, intuitive journeys online. Existing grocery services were failing on quality transparency, sustainable packaging, and navigation clarity.",
    insightCards: [
      { label: "Pain Point 01", text: "Poor quality transparency, shoppers couldn\u2019t verify freshness or provenance before purchasing.", highlight: false },
      { label: "Pain Point 02", text: "Excessive, non-recyclable packaging with no return or reuse pathway offered.", highlight: false },
      { label: "Pain Point 03", text: "Navigation wasn\u2019t store-like, category hierarchy was confusing, forcing heavy reliance on search.", highlight: true },
    ],
    research: "Five qualitative interviews were conducted over two weeks exploring how food plays a role in participants\u2019 daily lives. Two distinct user types emerged from the research.",
    researchCaption: "Research synthesis \u00B7 Affinity mapping in Miro",
    personas: [
      { name: "Joshua Chen", role: "The Home Cook \u00B7 Age 38 \u00B7 Seddon", bio: "Values quality, provenance, and Australian-grown products above all. Willing to pay a premium. Concerned about excess packaging." },
      { name: "Rachel Fletcher", role: "App/Service User \u00B7 Age 26 \u00B7 Glen Waverley", bio: "Currently uses meal kit services for convenience. Frustrated by bulky non-recyclable packaging. Actively tries to reduce her environmental footprint." },
    ],
    researchQuote: { text: "The cardboard box, the plastic packaging, the ice packs, every time I order, that stuff just goes straight in the bin. If they had a return service where they picked all that stuff up and dropped off the next one, I\u2019d be happy.", attribution: "Rachel Fletcher \u00B7 App/Service User Persona" },
    processIntro: "The process moved from research insights through information architecture, to lo-fi wireframes, usability testing, and a final iteration cycle.",
    processSteps: [
      { title: "Information Architecture", text: "Designed a store-like IA with clear category entry points, a recipes hub, and dedicated trust and returns content." },
      { title: "Lo-Fi Wireframes", text: "Built wireframes for Home, PLP, PDP, and Recipes." },
      { title: "Usability Testing (n=5)", text: "Five participants completed scripted tasks averaging 8m 53s. 100% defaulted to predictive search over flyout menus." },
      { title: "Iteration", text: "Simplified flyout labels, added category landing pages with visual cues, and introduced \u2018Shop Again\u2019 and recently-viewed patterns." },
    ],
    processCaption: "Lo-fi wireframes \u00B7 Home, PDP, Recipes pages",
    imgGrid2: [
      { alt: "Affinity map", caption: "Affinity map \u00B7 Research synthesis" },
      { alt: "Customer journey map", caption: "Customer journey map \u00B7 Awareness \u2192 Post-purchase" },
    ],
    solutionIntro: "The final solution brings together store-like navigation, strong product storytelling, and light-touch sustainability throughout the shopping journey.",
    solutionTiles: [
      { title: "Homepage", text: "Seasonal and local highlights, clear category entry tiles, prominent search, recipes rail, and a reusable packaging return explainer." },
      { title: "Product Listing (PLP)", text: "Tighter filters, dietary, Australian-grown, packaging type, with a consistent card layout." },
      { title: "Product Detail (PDP)", text: "Strong provenance storytelling, freshness and storage cues, recipe cross-links, and clear trust signals." },
      { title: "Recipes & Sustainability", text: "Browse recipes and auto-fill cart via \u201CShop this recipe.\u201D Packaging return program surfaced on PDP and at checkout." },
    ],
    solutionCaption: "Final UI set \u00B7 Home, Category landing, PLP, PDP, Recipes",
    youtubeEmbed: "https://youtu.be/qXsFpbLCgeA?si=37DLSIqRh3VmrZaN",
    outcomes: "Testing led to a clearer, category-first navigation that reduces dependence on predictive search.",
    keyOutcome: "A category-first IA with simplified flyouts and visual landing pages reduced navigation friction significantly.",
    reflection: "Grocery UX benefits most from store-like mental models online. IA clarity, predictable labels, and light-touch sustainability cues made the biggest difference, not visual polish.",
    reflectionQuote: { text: "Grocery shoppers expect to navigate the way they navigate a physical store. The moment that mental model breaks, when they can\u2019t find the aisle, they default to asking someone. Online, that\u2019s the search bar.", attribution: "Montague Joachim \u00B7 Reflection" },
  },
  {
    slug: "homepage-optimisation",
    projectName: "Officeworks, Homepage Optimisation",
    projectSlug: "OFFICEWORKS_HOMEPAGE_OPTIMISATION",
    coordLabel: "CS_007 \u00B7 CRO / Experimentation \u00B7 2024\u20132026",
    title: "Homepage Optimisation",
    discipline: "CRO / Experimentation",
    meta: [
      { label: "Role", value: "UX/UI Designer \u00B7 Experimentation & Personalisation (Web & Mobile)" },
      { label: "Timeline", value: "2024 \u2192 2026 \u00B7 Multi-cycle program \u00B7 Active" },
      { label: "Team", value: "CRO/Experimentation \u00B7 eComm Content/Trade \u00B7 Design \u00B7 Analytics" },
      { label: "Tools", value: "A/B testing infrastructure \u00B7 Figma \u00B7 Analytics \u00B7 Design system" },
      { label: "Scope", value: "Homepage strategy \u00B7 Modular/Bento system \u00B7 Hero \u00B7 Categories \u00B7 Recommendations \u00B7 Seasonal \u00B7 Mobile" },
    ],
    tldr: "A multi-year evolution of the Officeworks Homepage (2024\u20132026) focused on improving clarity, relevance, and the ability to guide customers into the right journeys.",
    overview: "The Officeworks Homepage carries a wide range of responsibilities, brand storytelling, promotions, navigation, and personalisation for very different customer intents. The challenge was improving clarity and relevance at scale.",
    problem: "Customers often struggled to quickly understand where to go next, what was most relevant to them, or how the Homepage related to their task. Unclear messaging hierarchy, over-reliance on promotional carousels, low-engagement regions, and limited contextual guidance were compounded by stakeholder and ops friction.",
    insightCards: [
      { label: "Pain Point 01", text: "Customers scan the Homepage quickly and make early decisions based on clarity, not persuasion. Promotional overload reduced confidence.", highlight: false },
      { label: "Pain Point 02", text: "Content cannibalisation, repeating the same trade story across multiple placements diluted the incremental value of each zone.", highlight: false },
      { label: "Pain Point 03", text: "Mobile fragility, long copy and tall imagery consistently pushed primary CTAs below the fold on small screens.", highlight: true },
    ],
    research: "Research combined a heuristic teardown, 2-year CRO journey mapping, behavioural analysis, customer feedback, and competitor benchmarking.",
    researchCaption: "CT-208 \u00B7 Category tiles redesign \u00B7 shipped to production",
    processIntro: "The program ran as an iterative learning loop, charter \u2192 test \u2192 learn \u2192 iterate, across four phases over 2024\u20132026.",
    processSteps: [
      { title: "Establishing Baselines", text: "Early tests focused on hero messaging, promotional emphasis, and value propositions. Results showed that stronger copy alone did not materially change behaviour." },
      { title: "Hierarchy & Orientation", text: "Subsequent experiments simplified the hero, clarified category entry points, and adjusted the balance between promotions and navigation." },
      { title: "Personalisation & Relevance", text: "Later tests introduced contextual and audience-based variations. Personalisation performed best when it removed irrelevant content." },
      { title: "Synthesis & Scale", text: "Insights were consolidated into design rules, a one-job-per-zone operating model, mobile-first constraints, curation guardrails, and lightweight governance." },
    ],
    processCaption: "CT-209 \u00B7 Full-width hero \u00B7 double-digit lift \u00B7 shipped to production",
    imgGrid2: [
      { alt: "Placement Purpose Map", caption: "Placement Purpose Map \u00B7 One job per zone, Wayfinding / Trade / Discovery / Supplier" },
      { alt: "Mobile-first constraints", caption: "Mobile-first constraints \u00B7 Copy limits, image ratios, CTA visibility thresholds" },
    ],
    solutionIntro: "The final solution is not a single screen, it\u2019s a coordinated operating model that prevents the Homepage competing with itself.",
    solutionTiles: [
      { title: "One Job Per Zone", text: "Wayfinding always present and prominent. Trade owns the primary campaign moment. Discovery adds distinct value only. Supplier is governed premium real estate." },
      { title: "Mobile-First Constraints", text: "Non-negotiable copy length, image ratio rules, and CTA visibility thresholds that preserve core actions on small screens." },
      { title: "Curation Rules", text: "Complement the hero, attach/adjacent categories, brand spotlights, price-led hot drops. Never repeat the same trade story in Discovery zones." },
      { title: "Governance & RACI", text: "Zone eligibility and duplication rules, mobile-readiness checks, SKU strength checks, and clear approvals." },
    ],
    solutionCaption: "Homepage operating model \u00B7 One-job-per-zone framework with mobile-first constraints",
    experiments: [
      { id: "CT-208", name: "Categories / Tiles (Wayfinding)", hypothesis: "Elevating categories and improving tile scannability will strengthen discovery paths.", resultValue: "Meaningful \u2191", resultLabel: "Discovery engagement \u00B7 Shipped \u2B50" },
      { id: "CT-209", name: "Hero Full-Width (Clarity)", hypothesis: "A full-width, decluttered hero will improve above-the-fold clarity.", resultValue: "Double-digit \u2191", resultLabel: "Hero interaction \u00B7 Shipped \u2B50" },
      { id: "CT-210", name: "Recommendations Simplification", hypothesis: "Reducing rec density will lower cognitive load.", resultValue: "Low single-digit \u2191", resultLabel: "Continuation \u00B7 Kept" },
      { id: "CT-314", name: "Themed Recommendations", hypothesis: "Manually curated themes will outperform algorithmic baseline.", resultValue: "Underperformed", resultLabel: "Cannibalisation confirmed \u00B7 Rules added" },
      { id: "CT-223", name: "Seasonal Journey (Mother\u2019s Day)", hypothesis: "Routing seasonal clicks to a shop-ready PLP will drive stronger discovery.", resultValue: "Substantial \u2191", resultLabel: "Discovery & ATC \u00B7 Adopted situationally" },
      { id: "CT-300", name: "Search-Term Pills (Intent Strip)", hypothesis: "Surfacing popular search terms will reduce friction.", resultValue: "Neutral", resultLabel: "High engagement, neutral commercial \u00B7 Not always-on" },
      { id: "CT-306", name: "New & Trending Mobile Card", hypothesis: "Mobile-first card formats will improve engagement in low-performing regions.", resultValue: "Constraints adopted", resultLabel: "Mobile fragility confirmed \u00B7 Rules shipped" },
      { id: "CT-234/279", name: "Bento / Supplier-Funded", hypothesis: "A modular premium surface with short copy and visible CTAs will increase engagement.", resultValue: "Double-digit \u2191", resultLabel: "Mobile interaction \u00B7 Retained, governed" },
    ],
    outcomes: "The program moved from isolated component lifts to coordinated orchestration. The one-job-per-zone operating model was adopted across the team. All outcomes are directional.",
    keyOutcome: "Three variants shipped to production, CT-208 (category tiles), CT-209 (full-width hero), and CT-234/279 (Bento), with a coordinated one-job-per-zone operating model adopted by the team.",
    reflection: "What changed the game wasn\u2019t a single big win, it was coordinating how placements work together. The shift to a one-job-per-zone model, combined with mobile-first guardrails and simple governance, turned sporadic lifts into compounding improvements.",
  },
];

export function getCaseStudy(slug: string): CaseStudyData | undefined {
  return caseStudies.find((cs) => cs.slug === slug);
}

export function getAllSlugs(): string[] {
  return caseStudies.map((cs) => cs.slug);
}

